---

- name: "Deploy Backend Playbook." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - DATABASE_URL: "{{ lookup('env', 'DATABASE_URL')}}"
    - PORT: "{{ lookup('env', 'PORT')}}"
    - JWT_SECRET: "{{ lookup('env', 'JWT_SECRET')}}"
    - JWT_REFRESH_SECRET: "{{ lookup('env', 'JWT_REFRESH_SECRET')}}"
    - JWT_REFRESH_SECRET: "{{ lookup('env', 'JWT_REFRESH_SECRET')}}"
    - NODEMAILER_EMAIL: "{{ lookup('env', 'NODEMAILER_EMAIL')}}"
    - NODEMAILER_PASSWORD: "{{ lookup('env', 'NODEMAILER_PASSWORD')}}"
    - REDISCLOUD_URL: "{{ lookup('env', 'REDISCLOUD_URL')}}"
  
  roles:
    - deploy
